# Generated by Django 4.1.4 on 2022-12-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counterapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MySQLCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=16)),
                ("count", models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name="counter",
            old_name="sqlite_count_obj",
            new_name="count",
        ),
    ]
